### ISSUE TITLE
Found a defect

### ISSUE THREAD

**Issue by fanchuanster** [cplotts/snoopwpf#67] opened 2018-04-09 04:15 UTC
Message: The visual tree has been changed during a 'VisualTreeChanged' event.
Stacktrace:
   at System.Windows.Diagnostics.VisualDiagnostics.VerifyVisualTreeChangeCore(DependencyObject d)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.ClearValueCommon(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata)
   at System.Windows.DependencyObject.ClearValue(DependencyPropertyKey key)
   at System.Windows.BroadcastEventHelper.RemoveLoadedCallback(DependencyObject d, Object[] loadedPending)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by batzen** [comment] 2018-04-12 08:38
If you want someone to have a look at this you should add more details about what you did, how the issue could be reproduced and, to make it easy for everyone to reproduce your issue, add a small sample application demonstrating your issue.

**Comment by cplotts** [comment] 2018-08-02 20:05
@fanchuanster I am closing this issue due to lack of information. As @batzen points out, we can't really do much without more info. In fact, it is entirely possible (and maybe even likely given that I haven't seen an issue like this before) that the issue is on your end and in your software.

**Closed by cplotts** 2018-08-02 20:05 UTC
