### ISSUE TITLE
Snoop crash when application shutdown.

### ISSUE THREAD

**Issue by ShineSmile** [cplotts/snoopwpf#56] opened 2017-03-13 08:17 UTC
Message: OpenClipboard 失败 (异常来自 HRESULT:0x800401D0 (CLIPBRD_E_CANT_OPEN))
Stacktrace:
   在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   在 System.Windows.Clipboard.Flush()
   在 System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   在 System.Windows.Clipboard.SetDataInternal(String format, Object data)
   在 System.Windows.Clipboard.SetText(String text, TextDataFormat format)
   在 System.Windows.Clipboard.SetText(String text)
   在 Snoop.EditedPropertiesHelper.DumpObjectsWithEditedProperties()
   在 Snoop.SnoopUI.SnoopedWindowClosingHandler(Object sender, CancelEventArgs e)
   在 System.ComponentModel.CancelEventHandler.Invoke(Object sender, CancelEventArgs e)
   在 System.Windows.Window.OnClosing(CancelEventArgs e)
   在 System.Windows.Window.WmClose()
   在 System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by XplittR** [comment] 2017-03-23 10:20
Seems to be duplicate of #12

**Comment by batzen** [comment] 2018-12-15 09:05
We should be able to fix this by switching from the wpf clipboard to the windows forms clipboard as that one has a built in retry.

**Closed** 2019-01-14 20:21 UTC
Labels: bug

**Comment by cplotts** [comment] 2019-01-14 20:33
I wonder if this can even happen anymore ... since we've removed it from the time when the Snooped window is closed ... but we can be safe I suppose ... since I suppose it still could happen when the user activates the command.

**Comment by ShineSmile** [comment] 2019-01-15 10:13
GJ!
