### ISSUE TITLE
Broken on High DPI

### ISSUE THREAD

**Issue by nesteruk** [cplotts/snoopwpf#63] opened 2018-01-19 09:04 UTC
On a 4K display it looks like this:

![image](https://user-images.githubusercontent.com/469046/35142918-e3bad684-fd10-11e7-8ee3-6673a402f5d0.png)

**Comment by cplotts** [comment] 2018-08-02 20:16
Yuck. I am curious what your DPI settings are for this monitor.

**Comment by mitchcapper** [comment] 2018-11-02 18:05
I had this issue with the current release but not with the current master build.  I am guessing the shift to .net 4 fixed it.

**Comment by PixelatedPope** [comment] 2018-11-09 21:10
I get this issue constantly on a standard 1080p monitor.  But even worse.  It seems to happen more often when trying to run as administrator.  
![image](https://user-images.githubusercontent.com/18564140/48288235-aef64500-e428-11e8-90b5-7c0aa58ddee8.png)

I often end up using WPF Inspector to inspect snoop and modify the height to be 28, which is odd because the actual height is 2 instead of the expected 26.  

![image](https://user-images.githubusercontent.com/18564140/48288354-13b19f80-e429-11e8-9ab7-a724caa7d299.png)

Is it possible that I have some old settings sitting around from the previous version?

**Comment by mitchcapper** [comment] 2018-11-09 21:37
@PixelatedPope  are you able to try the source from master to see if you have the same issue?

**Comment by batzen** [comment] 2018-11-11 09:13
Just had a look at this and i think i fixed this already with d14579927124688a8c3f2a4102b16b78df5aab21

@nesteruk & @PixelatedPope Could you try to reproduce the issue using the latest CI-build version?
You can get that version from https://ci.appveyor.com/project/batzen/snoopwpf/builds/20207688/artifacts

**Comment by PixelatedPope** [comment] 2018-11-13 15:42
@batzen Seems to work!  I'll keep an eye on it, because the problem was intermittent for me.  But thanks for the fix.

Off topic I know, but I am first and foremost a designer sort of pushing my way into the code side of things (and am not very good with GitHub).  I'm interested in bringing the UI for snoop into the current century, but am having trouble building master currently.  Where can I get help getting it up and running?

**Comment by mitchcapper** [comment] 2018-11-13 15:53
@PixelatedPope thanks! For other projects even just photoshop/vector files are good enough, generally others are happy to break them up into the actual assets but if you want to learn great! Clone the repo to a local folder,  run " ./paket.cmd restore" OR manually add "Microsoft.PowerShell.3.ReferenceAssemblies" through the project nuget packages in VS.   
Open it in VS2017 community and compile.
Now a few things:
Two of the projects are CPP they require a windows platform SDK (can be installed through VS).  If you don't want to install the exact SDK the project uses it is not an issue, but in VS you will need to right click on each where it says "ManagedInjector[32|64]-4.0" in solution explorer and go to properties.  Change the SDK Version in the dropdown to one you have and then you should be good.

Would be happy to remotely do so for you using remote desktop or TeamViewer if you like.

**Comment by PixelatedPope** [comment] 2018-11-13 16:12
@mitchcapper Ah, it was that powershell reference step I was missing.  Might want to add that to the "How do I build snoop" section of the readme.  

Appreciate the offer for help, but I'm really only a beginner when it comes to GitHub public projects. I've been using WPF/XAML for 5+ years professionally.  I'm just more XAML than C# (So I have VS2017 Pro on my work station).  This would be my first time trying to contribute to an open source project, so the whole "how do I branch and do a pull request" will be the adventure.  Hopefully you like what I do with the UI!

**Comment by PixelatedPope** [comment] 2018-11-13 16:57
Ah, I've seen that before (the reason I can't use WPF Inspector, actually).  Thanks for the tip, I'll make sure to use explicit styling on anything I change.

**Comment by mrbcmorris** [comment] 2019-01-29 21:44
@batzen seems like we should be able to close this?  I just installed 2.10.0.0 and verified it fixed the issue

**Closed** 2019-01-29 21:50 UTC
Labels: bug
