### ISSUE TITLE
Crash with a Trigger using a Behavior<T> attached property 

### ISSUE THREAD

**Issue by ju2pom** [cplotts/snoopwpf#77] opened 2018-07-30 12:55 UTC
I just discovered the new release and immediately jumped on it !
The new Trigger Tab is a great addition but I found an issue that leads to a crash.
After some investigation I found that the exception occurs in `ConditionItem.cs` file because it cannot retrieve a `DependencyPropertyDescriptor`.

It can happen when the dependency property is an attached property of a `Behavior<T>`.
I could easily make a simple workaround on a local build for Snoop, but hope you can find a more elegant solution.

**Comment by ju2pom** [comment] 2018-07-30 15:18
While I was building a small repro for you, I just figured out why it didn't work.
We have in our application a behavior (using blend `Behavior<T>`) which have two **attached** properties but none of them declare the static accessors.

What is very surprising is that in the small repro project it does not even compile whereas in our BIG project it does ...

So if it's legit to not implement those static accessors I guess Snoop should handle it correctly, if they are really mandatory then it's ok.

**Comment by batzen** [comment] 2018-07-30 17:54
Even if it's not legit it shouldn't cause snoop to cause a crash.
Could you attach your repro?

**Comment by ju2pom** [comment] 2018-07-31 10:41
The problem with the repro I made is it doesn't compile because of those missing accessors. Even though I send you repro that mimics what our application does.
[SnoopIssue.zip](https://github.com/cplotts/snoopwpf/files/2244970/SnoopIssue.zip)

**Comment by batzen** [comment] 2018-07-31 10:47
Thx.
Will have a look as soon as i got some spare time.

**Comment by batzen** [comment] 2018-09-09 12:26
Can reproduce your issue and it compiles fine as long as you either have the setter or the getter method.
Only refuses to compile here if i remove both.
Omitting the Setter does not cause a crash, but removing the getter causes a crash.

Will try to find a way to work around such issues.

**Comment by cplotts** [comment] 2018-10-01 18:07
@ju2pom so, the get and set accessors are only required ... based on how you are using the attached property. since you are using it in a trigger where you are evaluating the value ... only the get accessor is strictly necessary.

There could easily be a situation where you don't even use xaml to access the attached property ... and of course, then neither the get or set accessor is strictly necessary.

**Comment by cplotts** [comment] 2018-10-01 18:14
@ju2pom Ok weird. I just downloaded your sample project and tried it out. You do have to comment out both the set and get methods ... for it not to compile.

But ... if you comment out only one of the get or set methods ... it does compile ... and it does work. In particular, even if you comment out the get method ... **it works** ... which is super weird.

I guess my understanding was incorrect. I assume the code that parsed the xaml was needing those accessor methods ... but it must not.

**Comment by cplotts** [comment] 2018-10-01 18:41
@batzen ok ... i think i'm finally caught up here. i now can see the exception when you omit the get accessor and navigate to the Triggers tab ... and then select a visual that would show the trigger.

As to how Snoop should handle this ... I think this situation is pretty much an edge case and so I think throwing an exception here is completely valid. I do like the idea of providing more information with more meaningful information ... like what you suggest (i.e. "DependencyPropertyDescriptor could not be found. In case of an attached property this might be caused by a missing "get"-method for that property.").

I do not think we need to go to the lengths of showing a warning in the Snoop user interface.

**Comment by ju2pom** [comment] 2018-10-01 20:40
@cplotts Thanks for investigating this issue. As for me preventing Snoop from crashing would a good start. If Snoop could in addition put some red warning like for broken binding it would be ideal.

**Comment by cplotts** [comment] 2018-10-01 22:49
@ju2pom thanks for the input. I am not seeing a crash ... I am only seeing an unhandled exception. That's what you mean by crash, right?

After thinking about it some more, maybe I lean toward trying to create some kind of substitute name like @batzen was suggesting with DependencyProperty.OwnerType + DependencyProperty.Name. The downside to that, though, is that not having those set and get accessors for your attached properties is actually an issue and I would prefer that we let the WPF developer know that somehow. So I don't know what approach is better ... lol!

Maybe the best solution would be to create a substitute name so we don't throw an exception, highlight the attached property name somehow, and then indicate to the user the issue with a tool tip or popup (which we don't even do for a broken data binding).

Given that it is an edge case ... it probably comes down to weighing the effort in doing the above... against simply adding more information to the exception that is thrown.

I accept pull requests. :+1:

**Comment by batzen** [comment] 2018-10-07 20:52
Current implementation looks like this:
![image](https://user-images.githubusercontent.com/1971030/46586781-91c60380-ca83-11e8-9d24-065a7027cd90.png)

@cplotts would that be ok?

**Comment by ju2pom** [comment] 2018-10-08 07:27
Looks great to me 👍

**Comment by batzen** [comment] 2018-10-08 15:40
Or this way:
![image](https://user-images.githubusercontent.com/1971030/46618993-35192600-cb21-11e8-9142-185383c18e77.png)

**Comment by cplotts** [comment] 2018-10-11 22:41
Merged https://github.com/cplotts/snoopwpf/pull/90 into master. Closing.

**Closed by cplotts** 2018-10-11 22:41 UTC
